name: emart
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animate_do: ^3.1.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  chewie: ^1.3.2
  cloud_firestore_web: ^3.3.3
  collection: ^1.15.0
  connectivity: ^3.0.6
  crypto: ^3.0.3
  device_info: ^2.0.2
  dropdown_button2: ^1.4.0
  email_validator: ^2.0.1
  firebase_analytics: ^10.1.4
  firebase_analytics_web: ^0.5.1+12
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  firebase_storage: null
  flutter:
    sdk: flutter
  flutter_dash: ^1.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_localizations: 
    sdk: flutter
  flutter_pdfview: ^1.2.5
  flutter_svg: ^2.0.7
  flutter_uxcam: ^2.3.0
  # fuzzy: ^0.3.0
  fuzzywuzzy: ^1.1.2
  get: null
  get_storage: null
  gif: ^2.2.0
  google_tag_manager: ^0.1.0
  hexcolor: ^3.0.1
  http: ^1.1.0
  # imagebutton: ^0.0.6
  intl: ^0.18.1
  local_auth: ^2.1.2
  local_auth_ios: ^1.1.3
  onesignal_flutter: ^3.0.0
  overlay_support: ^2.1.0
  package_info: ^2.0.2
  permission_handler: ^11.0.1
  pinch_zoom_image_last: ^0.4.1
  progress_dialog_null_safe: ^1.0.7
  provider: ^6.0.0
  shared_preferences: ^2.0.17
  syncfusion_flutter_pdfviewer: ^23.1.40
  toggle_switch: ^2.0.1
  url_launcher: ^6.0.12
  video_player: ^2.4.7
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_launcher_icons: null
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptative_icen_background: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icon/
    - assets/icon/botones_soporte/
    - assets/image/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RoundedMplus1c
      fonts:
        - asset: assets/fonts/RoundedMplus1c-Black.ttf
        - asset: assets/fonts/RoundedMplus1c-Bold.ttf
        - asset: assets/fonts/RoundedMplus1c-ExtraBold.ttf
        - asset: assets/fonts/RoundedMplus1c-Light.ttf
        - asset: assets/fonts/RoundedMplus1c-Medium.ttf
        - asset: assets/fonts/RoundedMplus1c-Regular.ttf
        - asset: assets/fonts/RoundedMplus1c-Thin.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
